package it.cnr.icar.biograkn.go;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Classe Java per anonymous complex type.
 * 
 * <p>Il seguente frammento di schema specifica il contenuto previsto contenuto in questa classe.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="format-version" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="data-version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="saved-by" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="auto-generated-by" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subsetdef" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="synonymtypedef">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="scope" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="default-namespace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="remark" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ontology" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "formatVersion",
    "dataVersion",
    "date",
    "savedBy",
    "autoGeneratedBy",
    "subsetdef",
    "synonymtypedef",
    "defaultNamespace",
    "remark",
    "ontology"
})
@XmlRootElement(name = "header")
public class Header {

    @XmlElement(name = "format-version")
    protected float formatVersion;
    @XmlElement(name = "data-version", required = true)
    protected String dataVersion;
    @XmlElement(required = true)
    protected String date;
    @XmlElement(name = "saved-by", required = true)
    protected String savedBy;
    @XmlElement(name = "auto-generated-by", required = true)
    protected String autoGeneratedBy;
    protected List<Header.Subsetdef> subsetdef;
    @XmlElement(required = true)
    protected Header.Synonymtypedef synonymtypedef;
    @XmlElement(name = "default-namespace", required = true)
    protected String defaultNamespace;
    @XmlElement(required = true)
    protected String remark;
    @XmlElement(required = true)
    protected String ontology;

    /**
     * Recupera il valore della proprietà formatVersion.
     * 
     */
    public float getFormatVersion() {
        return formatVersion;
    }

    /**
     * Imposta il valore della proprietà formatVersion.
     * 
     */
    public void setFormatVersion(float value) {
        this.formatVersion = value;
    }

    /**
     * Recupera il valore della proprietà dataVersion.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataVersion() {
        return dataVersion;
    }

    /**
     * Imposta il valore della proprietà dataVersion.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataVersion(String value) {
        this.dataVersion = value;
    }

    /**
     * Recupera il valore della proprietà date.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Imposta il valore della proprietà date.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Recupera il valore della proprietà savedBy.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSavedBy() {
        return savedBy;
    }

    /**
     * Imposta il valore della proprietà savedBy.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSavedBy(String value) {
        this.savedBy = value;
    }

    /**
     * Recupera il valore della proprietà autoGeneratedBy.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoGeneratedBy() {
        return autoGeneratedBy;
    }

    /**
     * Imposta il valore della proprietà autoGeneratedBy.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoGeneratedBy(String value) {
        this.autoGeneratedBy = value;
    }

    /**
     * Gets the value of the subsetdef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subsetdef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubsetdef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Obo.Header.Subsetdef }
     * 
     * 
     */
    public List<Header.Subsetdef> getSubsetdef() {
        if (subsetdef == null) {
            subsetdef = new ArrayList<Header.Subsetdef>();
        }
        return this.subsetdef;
    }

    /**
     * Recupera il valore della proprietà synonymtypedef.
     * 
     * @return
     *     possible object is
     *     {@link Obo.Header.Synonymtypedef }
     *     
     */
    public Header.Synonymtypedef getSynonymtypedef() {
        return synonymtypedef;
    }

    /**
     * Imposta il valore della proprietà synonymtypedef.
     * 
     * @param value
     *     allowed object is
     *     {@link Obo.Header.Synonymtypedef }
     *     
     */
    public void setSynonymtypedef(Header.Synonymtypedef value) {
        this.synonymtypedef = value;
    }

    /**
     * Recupera il valore della proprietà defaultNamespace.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultNamespace() {
        return defaultNamespace;
    }

    /**
     * Imposta il valore della proprietà defaultNamespace.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultNamespace(String value) {
        this.defaultNamespace = value;
    }

    /**
     * Recupera il valore della proprietà remark.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Imposta il valore della proprietà remark.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemark(String value) {
        this.remark = value;
    }

    /**
     * Recupera il valore della proprietà ontology.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOntology() {
        return ontology;
    }

    /**
     * Imposta il valore della proprietà ontology.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOntology(String value) {
        this.ontology = value;
    }


    /**
     * <p>Classe Java per anonymous complex type.
     * 
     * <p>Il seguente frammento di schema specifica il contenuto previsto contenuto in questa classe.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "name"
    })
    public static class Subsetdef {

        @XmlElement(required = true)
        protected String id;
        @XmlElement(required = true)
        protected String name;

        /**
         * Recupera il valore della proprietà id.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Imposta il valore della proprietà id.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Recupera il valore della proprietà name.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Imposta il valore della proprietà name.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }


    /**
     * <p>Classe Java per anonymous complex type.
     * 
     * <p>Il seguente frammento di schema specifica il contenuto previsto contenuto in questa classe.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="scope" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "name",
        "scope"
    })
    public static class Synonymtypedef {

        @XmlElement(required = true)
        protected String id;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String scope;

        /**
         * Recupera il valore della proprietà id.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Imposta il valore della proprietà id.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Recupera il valore della proprietà name.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Imposta il valore della proprietà name.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Recupera il valore della proprietà scope.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScope() {
            return scope;
        }

        /**
         * Imposta il valore della proprietà scope.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScope(String value) {
            this.scope = value;
        }

    }

}

